### ISSUE TITLE
Create a public mirror of this repo too?

### ISSUE THREAD

**Issue by TheoPannetier** [RangeShifter/RScore#11]
I feel it would make sense to also have a public repo of the core code too, after all.
This would help with readability of the repo structure and use of subtrees.
Without a public mirror, having the subtrees referring to an invisible (private) repo may be confusing to external users and collaborators.
External contributors can also not contribute to the core code, or will do so in the subtrees in RangeShifter_batch or RangeShiftR-package, which we want to avoid (+so far, we haven't found a way to pull changes from subtrees to RScore!)

**Comment by TheoPannetier** [comment]
@JetteReeg what's your opinion on this?

**Comment by JetteReeg** [comment]
Hi Theo, I am a bit indecisive. 
I think this is also part of the whole discussion whether we make all repositories public (and thus don't need the mirrored repos anymore). If I remember correctly, we decided that whoever would like to collaborate should contact us (or better Justin/Greta/Damaris) and will get access to the private repos? So there won't be really external contributors? Until now I think it never occurred that anyone else outside of our team would fix/find bugs and create a pull request.
But understand your point. The ReadMes or guidance for contribution would probably only make sense for the private repositories and not necessarily for the public mirror, where the subtree structure should not be an important information. 
Maybe it would be enough to state that external collaborators, who found a bug in the code should not fix the bug on their own, but open an issue describing the bug and making a suggestion for a fix and we will incroporate the fix in the private repos + push it to the mirror?
I guess we should have a meeting with the whole team soonish to discuss the whole private/public issue?

**Comment by TheoPannetier** [comment]
I agree, we should first sort out the private/public issue and discuss a contributor policy with the larger group first.
I'm mothballing this issue (and https://github.com/RangeShifter/RangeShifter_batch_dev/issues/13) until then.
