### ISSUE TITLE
RangeshiftR still builds with release-common version of RScode

### ISSUE THREAD

**Issue by TheoPannetier** [RangeShifter/RScore#4]
Before merging it to `develop` (and then `master`) , we need to make sure that we can still build RangeShiftR using the single-release version of RScore on branch `release-common`.

**Comment by JetteReeg** [comment]
I was able to compile the R package. I am still checking if this version reproduce the Rpackage tutorials

**Comment by JetteReeg** [comment]
There were some minor differences in tutorial 1, which I relate to stochasticity, but also some minor differences in tutorial 2, when actually a seed is set. So I would have expected no differences at all. I will dig a bit deeper into it and would compare the results presented in the tutorials with the current release version. But I guess we could nevertheless go on and continue? So the next step would be to merge release-common first into develop?

**Comment by TheoPannetier** [comment]
Great! I'll close this issue then and proceed with the merge :)
Feel free to re-open this if you find something unsatisfactory in the tutorials output.
